import { ConflictException } from "@nestjs/common";

const WORDS_BY_LENGTH: Record<number, string[]> = {
  5: [
    "divin",
    "venin",
    "treve",
    "dring",
    "fonte",
    "usage",
    "filon",
    "epine",
    "perte",
    "abord",
    "juste",
    "paddy",
    "wouah",
    "porte",
    "grave",
    "loupe",
    "ovule",
    "bonne",
    "paien",
    "merle",
    "fouet",
    "secte",
    "clown",
    "tente",
    "cidre",
    "strip",
    "taupe",
    "patio",
    "vaine",
    "patte",
  ],
  6: [
    "truite",
    "tribun",
    "brelan",
    "sprint",
    "rocher",
    "averti",
    "traque",
    "purete",
    "volley",
    "dindon",
    "rosbif",
    "cheque",
    "spring",
    "degage",
    "ferree",
    "majeur",
    "sucree",
    "boulon",
    "baleze",
    "cirque",
    "allume",
    "whisky",
    "bodega",
    "accuse",
    "longue",
    "autour",
    "treuil",
    "tripot",
    "consul",
    "oracle",
  ],
  7: [
    "eloigne",
    "ginseng",
    "tartare",
    "bouquet",
    "balourd",
    "melasse",
    "facette",
    "joyeuse",
    "avancee",
    "recital",
    "peniche",
    "insulte",
    "anneaux",
    "aiguise",
    "balance",
    "etendue",
    "deserte",
    "milieux",
    "melodie",
    "refugie",
    "booster",
    "retrait",
    "routeur",
    "enervee",
    "gaterie",
    "degaine",
    "conseil",
    "fourgon",
    "smoking",
    "caution",
  ],
};

export function pickWordleWord(wordLength: number): string {
  const bank = WORDS_BY_LENGTH[wordLength];

  if (!bank || bank.length === 0) {
    throw new ConflictException(
      `Aucune banque de mots Wordle n'est disponible pour ${wordLength} lettres`,
    );
  }

  return bank[Math.floor(Math.random() * bank.length)];
}
