DROP TABLE IF EXISTS "Leaderboard";
DROP TABLE IF EXISTS "PlayerAnswer";
DROP TABLE IF EXISTS "GameQuestion";
DROP TABLE IF EXISTS "Game";
DROP TABLE IF EXISTS "Messages";
DROP TABLE IF EXISTS "RoomPlayer";
DROP TABLE IF EXISTS "Room";

DROP TYPE IF EXISTS "GameStatus";
DROP TYPE IF EXISTS "RoomGameType";
DROP TYPE IF EXISTS "RoomStatus";
