export { default as FriendsPage } from "./FriendsPage";
export { default as HomePage } from "./HomePage";
export { default as LoginPage } from "./LoginPage";
export { default as NotFound } from "./NotFound";
export { default as PrivacyPolicyPage } from "./PrivacyPolicyPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as QuizAdminPage } from "./QuizAdminPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as TermsOfServicePage } from "./TermsOfServicePage";
